[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "api", "migration"]

[profile.release]
strip = true
lto = true
