//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "newsletter_issues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub newsletter_issue_id: Uuid,
    pub title: String,
    pub text_content: String,
    pub html_content: String,
    pub published_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
