//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::{
    newsletter_issues::Entity as NewsletterIssues,
    subscription_tokens::Entity as SubscriptionTokens, subscriptions::Entity as Subscriptions,
    user::Entity as User,
};
