//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub name: String,
    pub subscribed_at: DateTimeWithTimeZone,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::subscription_tokens::Entity",
        from = "Column::Id",
        to = "super::subscription_tokens::Column::SubscriberId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SubscriptionTokens,
}

impl Related<super::subscription_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
